{% set name = "mdslw" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/razziel89/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 02c3bf9e6f4df02f4867c9a83be246c5491088a3c0a373f10cc8d834bf3d73df

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/razziel89/{{ name }}
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: Prepare your markdown for easy diff'ing!
  dev_url: https://github.com/razziel89/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
