context:
  version: "0.17.0"

package:
  name: mdslw
  version: ${{ version }}

source:
  url: https://github.com/razziel89/mdslw/archive/${{ version }}.tar.gz
  sha256: 687b2a2dd76b45055e61f33b0c72de802b196dc29fb3775cdc52bdec6b480fa0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - mdslw --help

about:
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: "Prepare your markdown for easy diff'ing!"
  homepage: https://github.com/razziel89/mdslw
  repository: https://github.com/razziel89/mdslw

extra:
  recipe-maintainers:
    - danielnachun
