context:
  version: "0.15.2"

package:
  name: mdslw
  version: ${{ version }}

source:
  url: https://github.com/razziel89/mdslw/archive/${{ version }}.tar.gz
  sha256: 4bfd409054c20a403d9f8e7b4b3f11dabf421752507ed5da4381bc3515caa39f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - mdslw --help

about:
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: "Prepare your markdown for easy diff'ing!"
  homepage: https://github.com/razziel89/mdslw
  repository: https://github.com/razziel89/mdslw

extra:
  recipe-maintainers:
    - danielnachun
