context:
  version: "0.15.1"

package:
  name: mdslw
  version: ${{ version }}

source:
  url: https://github.com/razziel89/mdslw/archive/${{ version }}.tar.gz
  sha256: 1318a0c3f685bb221c754e48b431c3ccf784eedad8ace49831ed32b4ebec45fa

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - mdslw --help

about:
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: "Prepare your markdown for easy diff'ing!"
  homepage: https://github.com/razziel89/mdslw
  repository: https://github.com/razziel89/mdslw

extra:
  recipe-maintainers:
    - danielnachun
