context:
  version: "0.17.1"

package:
  name: mdslw
  version: ${{ version }}

source:
  url: https://github.com/razziel89/mdslw/archive/${{ version }}.tar.gz
  sha256: 4dadf34036002909b1c2e547facb88b37a3a3ac0cc102d9a924fcc0161db1637

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - mdslw --help

about:
  license: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml
  summary: "Prepare your markdown for easy diff'ing!"
  homepage: https://github.com/razziel89/mdslw
  repository: https://github.com/razziel89/mdslw

extra:
  recipe-maintainers:
    - danielnachun
